version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: shopmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "80:80"
    depends_on:
      - mongodb

volumes:
  mongo-data: